name = "RayTracing"
uuid = "8c93b9f4-ff46-4ca5-8b4c-7f50415580d2"
authors = ["Joaquín Rodríguez <joaq.rod0@gmail.com>"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExtension = "Makie"

[compat]
GeometryBasics = "0.4"
LinearAlgebra = "1"
StaticArrays = "1"
